name: build

on:
  push:
    branches: [main, github-actions-windows-build]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
            shell: bash
          - name: macos
            os: macos-latest
            shell: bash
          - name: windows
            os: windows-latest
            shell: msys2 {0}

    name: build (${{ matrix.name }})
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install dependencies (linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update && sudo apt install -y build-essential cmake ninja-build libudev-dev

      - name: install dependencies (windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: >-
            mingw-w64-clang-x86_64-toolchain
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-ninja

      - name: configure
        run: |
          cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: build
        run: |
          cmake --build build

      - name: upload artifacts (windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: serialosc-windows
          path: build/bin/
          if-no-files-found: warn
